<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <SonarQubeTestProject>false</SonarQubeTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VirtoCommerce.Platform.Data" Version="3.1007.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Virtocommerce.Backuprestore.Core\Virtocommerce.Backuprestore.Core.csproj" />
  </ItemGroup>
</Project>
