<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <SonarQubeTestProject>true</SonarQubeTestProject>
    <NoWarn>NU1608</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="[7.2.2, 8.0.0)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\VirtoCommerce.BackupRestore.Core\VirtoCommerce.BackupRestore.Core.csproj" />
    <ProjectReference Include="..\..\src\VirtoCommerce.BackupRestore.Data\VirtoCommerce.BackupRestore.Data.csproj" />
    <ProjectReference Include="..\..\src\VirtoCommerce.BackupRestore.Web\VirtoCommerce.BackupRestore.Web.csproj" />
  </ItemGroup>
</Project>
